apiVersion: apps/v1
kind: Deployment
metadata:
  name: snakecore-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snakecore-web
  template:
    metadata:
      labels:
        app: snakecore-web
    spec:
      containers:
      - name: snakecore-web
        image: jonanders/snakecore:1.1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: snakecore-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: snakecore-web